### ISSUE TITLE
The Quickref documentation needs to be updated

### ISSUE THREAD

**Issue by phoe** [TBRSS/cl-yesql#10]
https://quickref.common-lisp.net/cl-yesql.html

![Zrzut ekranu z 2019-03-19 22-14-11](https://user-images.githubusercontent.com/15045546/54642215-5731af80-4a94-11e9-8d6f-cb0f8892587c.png)

I assume this is supposed to mention Vernacular and not Overlord anymore.

**Comment by ruricolist** [comment]
I don't know anything about Quickref, except that it comes up a lot in Google search results and is seriously out of date.

**Comment by phoe** [comment]
![Zrzut ekranu z 2019-03-21 08-29-47](https://user-images.githubusercontent.com/15045546/54738198-80952d00-4bb3-11e9-934a-f5ce406be92b.png)

Well... no doubt.

**Comment by phoe** [comment]
I've let Didier know about it - let's see what his answer is.

**Comment by phoe** [comment]
Got an answer from him and raised https://gitlab.common-lisp.net/quickref/quickref/issues/2.

**Comment by phoe** [comment]
Quickref now autoupdates.

**Comment by ruricolist** [comment]
Thanks. You've done a public service.
