### ISSUE TITLE
Comments in YeSQL files

### ISSUE THREAD

**Issue by phoe** [TBRSS/cl-yesql#2]
How do I put comments in yesql files if comments are interpreted by the parser?

I want a comment that is not meant to be attached to any particular SQL query, like:

```sql
-------------------------------------
-- Foo Bar library
-- © 2017 Fred Baz Quux

-- name: user-count
-- Counts all the users.
SELECT count(*) AS count
FROM user
```

Is the above going to work properly, like, the initial lines won't get attached to the query?

Also, are the SQL "docstrings" automatically inserted into Lisp functions' documentation strings?

**Comment by ruricolist** [comment]
Free comments are not supported. At the moment the grammar in cl-yesql is an exact copy of the grammar of Clojure's yesql, and it doesn't support free comments.

SQL "docstrings" are, in fact, attached as docstrings for the exported Lisp functions, though whether they are actually visible in the final Lisp bindings depends on how the functions are imported.

**Comment by phoe** [comment]
I see - thank you. Maybe I can make a PR where comments starting with `----` (four hyphens instead of two) are actually treated as free comments and completely ignored.
