### ISSUE TITLE
Add collected keys to the function's &KEY in lambda list

### ISSUE THREAD

**Issue by phoe** [TBRSS/cl-yesql#7]
```sql
-- name: insert-new-player @execute
-- Inserts a new player into the database.
INSERT INTO player (player_name, email, passhash)
  VALUES(:player_name, :email, :passhash);
```

Currently, this function has a signature `(insert-new-player &rest args)`.
It should be possible to collect the list of used keys though (I can bet $5 you already do this internally) and insert them into the function's argument list, and therefore turn the function signature into a more appropriate `(insert-new-player :player-name :email :passhash)`.

**Comment by phoe** [comment]
This issue is actually deeper than just that.

Currently, CL-YESQL has no way of naming positional arguments and generating meaningful lambda lists, *despite* having all the required information in form of how many arguments there are, in which order they appear in the query, and what is their name (in case of keyword arguments).

Additionally, keyword arguments are not treated as optional in CL-YESQL, despite their usual function in Common Lisp as being "modifiers".

I will be thinking on how to solve this. One thing that I can think of is replacing `?` with `?foo` where `foo` will be the argument name in the function's lambda list. If no name is supplied, it may default to `argN` where `N` is the number of the argument in the query.

**Comment by ruricolist** [comment]
CL-Yesql itself actually does save argument information (and documentation, as in #6). The problem is with the way imports are (currently) handled: functions are not bound directly, but through an indirection, to make sure redefinitions are picked up.

There may be a better way to handle this; I need to think about it.

**Comment by phoe** [comment]
See ASDF:WITH-UPGRADABILITY to see how ASDF deals with that.

https://github.com/fare/asdf/blob/master/uiop/utility.lisp#L65

Dnia 6 kwietnia 2018 00:36:29 CEST, "Paul M. Rodriguez" <notifications@github.com> napisał(a):
>CL-Yesql itself actually does save argument information (and
>documentation, as in #6). The problem is with the way imports are
>(currently) handled: functions are not bound directly, but through an
>indirection, to make sure redefinitions are picked up.
>
>There may be a better way to handle this; I need to think about it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TBRSS/cl-yesql/issues/7#issuecomment-379097225

-- Wysłane za pomocą K-9 Mail.

**Comment by phoe** [comment]
I don't think why you couldn't depend on ASDF for that macro if you already depend on ASDF for system definition. The trick is to inject at a proper place, so it comes directly before your `DEFUN`s - it only checks the CARs of its subforms and does not have a full codewalker.

**Comment by ruricolist** [comment]
This is supported now in the dev branch.
